version: "3.8"

services:
#  postgres:
#    container_name: r8-audit-test-postgres
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: MyPassWoRD@#$
#      POSTGRES_DB: r8-audit-test
#    ports:
#      - "54322:5432"
    
  mssql:
    container_name: r8-audit-test-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: MyPassWoRD@#$
      ACCEPT_EULA: Y,
      MSSQL_DATABASE: r8-audit-test,
    ports:
      - "14331:1433"